### ISSUE TITLE
update the IdP CSS

### ISSUE THREAD

**Issue by eitzhaki** [eedevops/he-identity-portal#38]
The UI/UX team have updated the mockup for the IdP it is located [here](https://zpl.io/Z12D64S)

**Comment by rqc** [comment]
@eitzhaki @JonathanRosado cross referencing issue #3 which has links to the `SASS` style files which should be used to implement the new look-and-feel.

**Comment by rqc** [comment]
@eitzhaki @JonathanRosado I've done some work towards this. It is under branch https://github.com/eedevops/he-identity-portal/tree/feature/redesign-portal-look-and-feel

Here is a snapshot of how it is looking thus far:

![image](https://cloud.githubusercontent.com/assets/89690/20026607/0b304e76-a2d4-11e6-8550-a06617636cdd.png)

**Comment by rqc** [comment]
Done.
